const GI_DATABASE = [
  {
    "id": "GI001",
    "gene_a_locus": "spd_1821",
    "gene_a": "pbp2a",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall/membrane biogenesis (PG synthesis, aPBP)",
    "func_b": "Cell wall/membrane biogenesis (PG synthesis, aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Recapitulated known synthetic lethal relationship between pbp1a and pbp2a using barcoded libraries"
  },
  {
    "id": "GI002",
    "gene_a_locus": "spd_0876",
    "gene_a": "macP",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall/membrane biogenesis (MacP cofactor, aPBP regulation)",
    "func_b": "Cell wall/membrane biogenesis (PG synthesis, aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Recapitulated known synthetic lethal between pbp1a and macP (spd_0876)"
  },
  {
    "id": "GI003",
    "gene_a_locus": "spd_0336",
    "gene_a": "pbp1a",
    "gene_b_locus": "spd_1040",
    "gene_b": "pbp1b",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.05",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall/membrane biogenesis (PG synthesis, aPBP)",
    "func_b": "Cell wall/membrane biogenesis (PG synthesis, aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Confirmed negative genetic interaction between pbp1a and pbp1b"
  },
  {
    "id": "GI004",
    "gene_a_locus": "spd_0310",
    "gene_a": "pyrJ",
    "gene_b_locus": "spd_0174",
    "gene_b": "pyrG",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq",
    "score": "FDR~7%",
    "pval": "<0.07",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Nucleotide metabolism (CTP synthase, ammonium-dependent)",
    "func_b": "Nucleotide metabolism (CTP synthase, glutamine-dependent)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "spd_0310 encodes a novel ammonium-dependent CTP synthase; cytidine supplementation rescues growth defect of delta-pyrG delta-spd0310"
  },
  {
    "id": "GI005",
    "gene_a_locus": "spd_0967",
    "gene_a": "murZ",
    "gene_b_locus": "spd_0981",
    "gene_b": "yjbK",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_Tn-seq",
    "score": "strong",
    "pval": "<0.10",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall/membrane biogenesis (UDP-MurNAc synthesis)",
    "func_b": "Cell wall/membrane biogenesis (MurA regulator)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Strong negative interaction between yjbK (spd_0981) and murZ; YjbK is regulatory factor specifically for MurA"
  },
  {
    "id": "GI006",
    "gene_a_locus": "spd_0967",
    "gene_a": "murZ",
    "gene_b_locus": "spd_1764",
    "gene_b": "murA",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq",
    "score": "validated",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall/membrane biogenesis (UDP-MurNAc synthesis)",
    "func_b": "Cell wall/membrane biogenesis (UDP-MurNAc synthesis)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Cells lacking both murZ and murA are nonviable; redundant UDP-GlcNAc carboxyvinyltransferases"
  },
  {
    "id": "GI007",
    "gene_a_locus": "spd_1910-1914",
    "gene_a": "pst1_operon",
    "gene_b_locus": "spd_1227-1232",
    "gene_b": "pst2_operon",
    "class": "negative",
    "subtype": "strong_negative",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Inorganic ion transport (phosphate, ABC transporter)",
    "func_b": "Inorganic ion transport (phosphate, ABC transporter)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Strong negative genetic interactions between genes of the two Pst phosphate import systems; redundant Pi transporters"
  },
  {
    "id": "GI008",
    "gene_a_locus": "spd_0556",
    "gene_a": "trkH",
    "gene_b_locus": "spd_0429",
    "gene_b": "spd_0429",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Inorganic ion transport (K+ uptake, TrkH)",
    "func_b": "Inorganic ion transport (K+ uptake, Trk-type)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "trkH and cabP form synthetic lethal pairs with spd_0429/spd_0430; at least one K+ system required"
  },
  {
    "id": "GI009",
    "gene_a_locus": "spd_0429",
    "gene_a": "cabP",
    "gene_b_locus": "spd_0430",
    "gene_b": "spd_0430",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Inorganic ion transport (K+ uptake)",
    "func_b": "Inorganic ion transport (K+ regulatory)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "cabP forms synthetic lethal pair with spd_0430; Spd_0430 is regulatory component of Trk-type K+ transporter"
  },
  {
    "id": "GI010",
    "gene_a_locus": "spd_0310",
    "gene_a": "pyrJ",
    "gene_b_locus": "spd_1425",
    "gene_b": "spd_1425",
    "class": "positive",
    "subtype": "suppressor",
    "method": "Dual_Tn-seq",
    "score": "positive_GI",
    "pval": "n.s.",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Nucleotide metabolism (CTP synthase)",
    "func_b": "Nucleoside transport (cytidine transporter)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "spd_1425 is primary cytidine transporter; overexpression alleviates growth defects of pyrJ-deficient cells"
  },
  {
    "id": "GI011",
    "gene_a_locus": "spd_1225",
    "gene_a": "pdxR",
    "gene_b_locus": "spd_1226-1227",
    "gene_b": "pdxST",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.05",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Coenzyme metabolism (PLP/B6 regulation)",
    "func_b": "Coenzyme metabolism (PLP/B6 de novo synthesis)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Strong negative interactions between pdxST and pdxR; pdxR activates pdxST expression; pathway redundancy"
  },
  {
    "id": "GI012",
    "gene_a_locus": "spd_1228",
    "gene_a": "pdxU2",
    "gene_b_locus": "spd_1226-1227",
    "gene_b": "pdxST",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.05",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Coenzyme metabolism (PLP/B6 salvage)",
    "func_b": "Coenzyme metabolism (PLP/B6 de novo synthesis)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Strong negative interactions between PdxST de novo synthesis and salvage pathway components PdxU2/PdxK"
  },
  {
    "id": "GI013",
    "gene_a_locus": "spd_0411-0412",
    "gene_a": "lysXY",
    "gene_b_locus": "multiple",
    "gene_b": "de_novo_lys_pathway",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_Tn-seq",
    "score": "high-confidence",
    "pval": "<0.05",
    "strain": "D39W",
    "condition": "in vitro (BHI rich medium)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Amino acid transport (lysine importer)",
    "func_b": "Amino acid biosynthesis (lysine de novo)",
    "validation": "confirmed_in_study",
    "pmid": "40997176",
    "doi": "10.1126/science.adt7685",
    "quote": "Strong negative interactions between lysine transporter lysXY and de novo lysine biosynthesis pathway genes"
  },
  {
    "id": "GI014",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_1005",
    "gene_b": "murM",
    "class": "negative",
    "subtype": "synthetic_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP, transpeptidase)",
    "func_b": "Cell wall biogenesis (PG branch formation, MurM)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "PG precursor synthesis genes murM, murN, murA1 important upon pbp2x knockdown; negative interactions"
  },
  {
    "id": "GI015",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_1006",
    "gene_b": "murN",
    "class": "negative",
    "subtype": "synthetic_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP, transpeptidase)",
    "func_b": "Cell wall biogenesis (PG branch formation, MurN)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "PG precursor synthesis important upon pbp2x knockdown"
  },
  {
    "id": "GI016",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_1764",
    "gene_b": "murA",
    "class": "negative",
    "subtype": "synthetic_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (UDP-MurNAc synthesis)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "PG precursor synthesis important upon pbp2x knockdown"
  },
  {
    "id": "GI017",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "positive",
    "subtype": "suppressor",
    "method": "CRISPRi-TnSeq",
    "score": "z>+1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "Deletion of pbp1a suppresses pbp2x knockdown; balances septal/peripheral PG synthesis"
  },
  {
    "id": "GI018",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_1040",
    "gene_b": "pbp1b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "CRISPRi-TnSeq",
    "score": "z>+1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "Deletion of pbp1b suppresses pbp2x knockdown; peripheral PG compensation"
  },
  {
    "id": "GI019",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_1821",
    "gene_b": "pbp2a",
    "class": "positive",
    "subtype": "suppressor",
    "method": "CRISPRi-TnSeq",
    "score": "z>+1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "Deletion of pbp2a suppresses pbp2x knockdown; peripheral PG compensation"
  },
  {
    "id": "GI020",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_0093",
    "gene_b": "pbp3",
    "class": "negative",
    "subtype": "strong_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.01",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (D-Ala-D-Ala hydrolase, CW remodeling)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "pbp3 hydrolyses d-Ala; directs PG to septum; strong negative with pbp2x knockdown"
  },
  {
    "id": "GI021",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_0040",
    "gene_b": "sepF",
    "class": "negative",
    "subtype": "strong_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.01",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell division (FtsZ ring assembly, SepF)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "sepF involved in Z-ring assembly; strong negative with pbp2x knockdown"
  },
  {
    "id": "GI022",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_1174",
    "gene_b": "pde1",
    "class": "positive",
    "subtype": "suppressor",
    "method": "CRISPRi-TnSeq",
    "score": "z>+1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Signal transduction (c-di-AMP phosphodiesterase)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "Delta-pde1 suppresses pbp2x knockdown; increased c-di-AMP maintains growth under reduced PBP2x"
  },
  {
    "id": "GI023",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_0747",
    "gene_b": "cozEa",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (CozE, membrane scramblase)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "cozEa in tight negative cluster with pbp2x; CW metabolism"
  },
  {
    "id": "GI024",
    "gene_a_locus": "spd_1160",
    "gene_a": "ftsZ",
    "gene_b_locus": "spd_0093",
    "gene_b": "pbp3",
    "class": "negative",
    "subtype": "strong_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.01",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (tubulin-like, Z-ring)",
    "func_b": "Cell wall biogenesis (CW remodeling)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "ftsZ and pbp3 strong negative; cell division coordination"
  },
  {
    "id": "GI025",
    "gene_a_locus": "spd_1160",
    "gene_a": "ftsZ",
    "gene_b_locus": "spd_0040",
    "gene_b": "sepF",
    "class": "negative",
    "subtype": "strong_negative",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.01",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (Z-ring)",
    "func_b": "Cell division (Z-ring assembly)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "ftsZ and sepF strong negative; Z-ring assembly"
  },
  {
    "id": "GI026",
    "gene_a_locus": "spd_1390",
    "gene_a": "fabH",
    "gene_b_locus": "spd_0437",
    "gene_b": "plsX",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Lipid metabolism (fatty acid synthesis, FabH)",
    "func_b": "Lipid metabolism (phospholipid synthesis, PlsX)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "Negative interaction fabH-plsX; PlsX compensates FabH by diverting acyl-ACP production"
  },
  {
    "id": "GI027",
    "gene_a_locus": "spd_0443",
    "gene_a": "parC",
    "gene_b_locus": "spd_1375",
    "gene_b": "parB",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "DNA replication/repair (topoisomerase IV, ParC)",
    "func_b": "Chromosome segregation (ParB, parS-binding)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "parC-parB negative; results in anucleate cells and uneven chromosome distribution"
  },
  {
    "id": "GI028",
    "gene_a_locus": "spd_0443",
    "gene_a": "parC",
    "gene_b_locus": "spd_0467",
    "gene_b": "smc",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "DNA replication/repair (topoisomerase IV)",
    "func_b": "Chromosome segregation (SMC condensin)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "parC-smc negative; chromosome decatenation/condensin interaction"
  },
  {
    "id": "GI029",
    "gene_a_locus": "spd_1174",
    "gene_a": "cdaA",
    "gene_b_locus": "spd_1174",
    "gene_b": "pde1",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (c-di-AMP synthase)",
    "func_b": "Signal transduction (c-di-AMP phosphodiesterase)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "cdaA-pde1 negative; c-di-AMP second messenger pathway balance"
  },
  {
    "id": "GI030",
    "gene_a_locus": "spd_0467",
    "gene_a": "smc",
    "gene_b_locus": "spd_0466",
    "gene_b": "scpA",
    "class": "negative",
    "subtype": "condensin_cluster",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Chromosome segregation (SMC condensin)",
    "func_b": "Chromosome segregation (SMC kleisin)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "smc-scpA-scpB form condensin complex cluster; chromosome compaction"
  },
  {
    "id": "GI031",
    "gene_a_locus": "spd_0747",
    "gene_a": "cozEa",
    "gene_b_locus": "spd_1005",
    "gene_b": "murM",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "CRISPRi-TnSeq",
    "score": "z<-1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (CozE)",
    "func_b": "Cell wall biogenesis (PG branching)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "cozEa negative with murM murN murA; septal PG synthesis"
  },
  {
    "id": "GI032",
    "gene_a_locus": "spd_0747",
    "gene_a": "cozEa",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "positive",
    "subtype": "suppressor",
    "method": "CRISPRi-TnSeq",
    "score": "z>+1.5",
    "pval": "<0.075",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 IPTG)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (CozE)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "39030344",
    "doi": "10.1038/s41564-024-01759-x",
    "quote": "cozEa positive interaction with pbp1a and pbp2a; suppressive relationship"
  },
  {
    "id": "GI033",
    "gene_a_locus": "spd_0747",
    "gene_a": "cozEa",
    "gene_b_locus": "spd_1094",
    "gene_b": "mreC",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-7",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (CozE)",
    "func_b": "Cell shape determination (MreC, elongasome)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "cozEa-mreC extreme negative; known synthetic lethal pair confirmed by dual CRISPRi-seq"
  },
  {
    "id": "GI034",
    "gene_a_locus": "spd_1821",
    "gene_a": "pbp2a",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-7",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (aPBP)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "independently_replicated",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "pbp1a-pbp2a classic synthetic lethal confirmed by dual CRISPRi-seq"
  },
  {
    "id": "GI035",
    "gene_a_locus": "spd_1093",
    "gene_a": "mreD",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell shape determination (MreD, elongasome)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "divIB-mreD negative; elongasome function"
  },
  {
    "id": "GI036",
    "gene_a_locus": "spd_1346",
    "gene_a": "mpgA",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon>+1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (MltG/MpgA, lytic transglycosylase)",
    "func_b": "Cell wall biogenesis (bPBP, transpeptidase)",
    "validation": "independently_replicated",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "mpgA-pbp2b positive interaction validated by dual CRISPRi and deletion; elongasome regulation"
  },
  {
    "id": "GI037",
    "gene_a_locus": "spd_1849",
    "gene_a": "eloR",
    "gene_b_locus": "spd_1166",
    "gene_b": "rodA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon>+1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding/regulation (KhpB/EloR, elongasome inhibitor)",
    "func_b": "Cell wall biogenesis (RodA, lipid II flippase)",
    "validation": "independently_replicated",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "rodA-eloR positive interaction validated; elongasome regulation; EloR/KhpA complex regulates elongasome"
  },
  {
    "id": "GI038",
    "gene_a_locus": "spd_0008",
    "gene_a": "divIB",
    "gene_b_locus": "spd_1166",
    "gene_b": "rodA",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell division (DivIB, FtsLQB complex)",
    "func_b": "Cell wall biogenesis (RodA, lipid II flippase)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "divIB-rodA negative; shared negative with elongasome machinery"
  },
  {
    "id": "GI039",
    "gene_a_locus": "spd_0008",
    "gene_a": "divIB",
    "gene_b_locus": "spd_1094",
    "gene_b": "mreC",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell division (FtsLQB)",
    "func_b": "Cell shape determination (elongasome)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "divIB-mreC negative; elongasome function"
  },
  {
    "id": "GI040",
    "gene_a_locus": "spd_0008",
    "gene_a": "divIB",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell division (FtsLQB)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "divIB-pbp2b negative; elongasome function"
  },
  {
    "id": "GI041",
    "gene_a_locus": "spd_0008",
    "gene_a": "divIB",
    "gene_b_locus": "spd_1346",
    "gene_b": "mpgA",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (FtsLQB)",
    "func_b": "Cell wall biogenesis (lytic transglycosylase)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "divIB-mpgA negative interaction validated by dual CRISPRi and deletion; round heterogeneous cells"
  },
  {
    "id": "GI042",
    "gene_a_locus": "spd_0467",
    "gene_a": "smc",
    "gene_b_locus": "spd_0747",
    "gene_b": "cozEa",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Chromosome segregation (SMC condensin)",
    "func_b": "Cell wall biogenesis (CozE, membrane scramblase)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "smc-cozEa negative; novel GI between membrane scramblase and SMC chromosome compaction complex"
  },
  {
    "id": "GI043",
    "gene_a_locus": "spd_0467",
    "gene_a": "smc",
    "gene_b_locus": "spd_1474",
    "gene_b": "ftsK",
    "class": "negative",
    "subtype": "negative_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-1",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Chromosome segregation (SMC)",
    "func_b": "Chromosome segregation (FtsK, DNA translocase)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "smc-ftsK negative; chromosome segregation"
  },
  {
    "id": "GI044",
    "gene_a_locus": "spd_0469",
    "gene_a": "scrA",
    "gene_b_locus": "spd_0468",
    "gene_b": "scrB",
    "class": "positive",
    "subtype": "positive_GI",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon>+1.5",
    "pval": "<0.05",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Carbon metabolism (sucrose PTS permease)",
    "func_b": "Carbon metabolism (sucrose-6-phosphatase)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "scrA-scrB positive interaction validated; sucrose metabolism pathway (condition-specific)"
  },
  {
    "id": "GI045",
    "gene_a_locus": "SPV_0761",
    "gene_a": "spv_0761",
    "gene_b_locus": "spd_0067",
    "gene_b": "hlpA",
    "class": "negative",
    "subtype": "extreme_negative",
    "method": "Dual_CRISPRi-Seq",
    "score": "epsilon<-7",
    "pval": "<0.01",
    "strain": "D39V",
    "condition": "in vitro (C+Y medium \u00b1 1 mM IPTG)",
    "ess_a": "unknown",
    "ess_b": "non-essential",
    "func_a": "Unknown function",
    "func_b": "Chromosome segregation (HlpA, HU-like)",
    "validation": "confirmed_in_study",
    "pmid": "41045936",
    "doi": "10.1016/j.cels.2025.101408",
    "quote": "spv_0761-hlpA extreme negative; proposed role in chromosome segregation"
  },
  {
    "id": "GI046",
    "gene_a_locus": "SPN23F03080",
    "gene_a": "pbp2x",
    "gene_b_locus": "SPN23F03410",
    "gene_b": "pbp1a",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP, beta-lactam target)",
    "func_b": "Cell wall biogenesis (aPBP, beta-lactam target)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "5199 significant couplings; PBP network (77.5% of couplings) involves pbp2x pbp1a pbp2b; 95% involve pbp2x"
  },
  {
    "id": "GI047",
    "gene_a_locus": "SPN23F03080",
    "gene_a": "pbp2x",
    "gene_b_locus": "SPN23F16740",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "3578 PBP-related links; concerted changes required for beta-lactam non-susceptibility"
  },
  {
    "id": "GI048",
    "gene_a_locus": "SPN23F03080",
    "gene_a": "pbp2x",
    "gene_b_locus": "SPN23F02680",
    "gene_b": "mraY",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Cell wall biogenesis (MraY, lipid I synthesis)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "mraY downstream pbp2x co-evolves in PBP resistance network"
  },
  {
    "id": "GI049",
    "gene_a_locus": "SPN23F03410",
    "gene_a": "pbp1a",
    "gene_b_locus": "SPN23F03430",
    "gene_b": "gpsB",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (aPBP)",
    "func_b": "Cell division (GpsB, adapter protein)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "gpsB upstream pbp1a co-evolves in PBP resistance network"
  },
  {
    "id": "GI050",
    "gene_a_locus": "SPN23F03080",
    "gene_a": "pbp2x",
    "gene_b_locus": "SPN23F16820",
    "gene_b": "dhfr",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (bPBP)",
    "func_b": "Nucleotide metabolism (DHFR, trimethoprim target)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "MDR co-evolution: PBP genes co-evolve with trimethoprim resistance gene dhfr/folA"
  },
  {
    "id": "GI051",
    "gene_a_locus": "SPN23F11420",
    "gene_a": "smc",
    "gene_b_locus": "multiple (22 CDSs)",
    "gene_b": "core_machinery",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "essential",
    "ess_b": "mixed",
    "func_a": "Chromosome segregation (SMC condensin)",
    "func_b": "Multiple (core cellular machinery)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "smc most connected gene in core machinery network; links to 22 CDSs; largest network component = 384 CDSs"
  },
  {
    "id": "GI052",
    "gene_a_locus": "SPN23F19090",
    "gene_a": "pspA",
    "gene_b_locus": "SPN23F08630",
    "gene_b": "divIVA",
    "class": "positive",
    "subtype": "co-evolutionary",
    "method": "population_genomics",
    "score": "Frobenius>0.129",
    "pval": ">6SD",
    "strain": "3156 clinical S. pneumoniae isolates",
    "condition": "natural population (clinical surveillance)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Virulence (PspA, choline-binding protein)",
    "func_b": "Cell division (DivIVA, division site organization)",
    "validation": "predicted",
    "pmid": "28207813",
    "doi": "10.1371/journal.pgen.1006508",
    "quote": "pspA and divIVA co-evolve in virulence gene network"
  },
  {
    "id": "GI053",
    "gene_a_locus": "spd_1346",
    "gene_a": "mltG",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative (>500 colonies)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (lytic transglycosylase)",
    "func_b": "Cell wall biogenesis (bPBP, transpeptidase)",
    "validation": "confirmed_in_study",
    "pmid": "26933838",
    "doi": "10.1111/mmi.13359",
    "quote": "Mutations inactivating MltG (Spd_1346) remove the requirement for essential PBP2b"
  },
  {
    "id": "GI054",
    "gene_a_locus": "spd_1346_Y488D",
    "gene_a": "mltG(Y488D)",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (lytic transglycosylase, gain-of-function)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "confirmed_in_study",
    "pmid": "26933838",
    "doi": "10.1111/mmi.13359",
    "quote": "Single mltG(Y488D) change suppresses requirement for PBP2b, MreCD, RodZ, and RodA"
  },
  {
    "id": "GI055",
    "gene_a_locus": "spd_1346_Y488D",
    "gene_a": "mltG(Y488D)",
    "gene_b_locus": "spd_1093-1094",
    "gene_b": "mreCD",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (lytic transglycosylase)",
    "func_b": "Cell shape determination (elongasome, MreCDE)",
    "validation": "confirmed_in_study",
    "pmid": "26933838",
    "doi": "10.1111/mmi.13359",
    "quote": "mltG(Y488D) suppresses DeltamreCD; peripheral PG synthesis genes"
  },
  {
    "id": "GI056",
    "gene_a_locus": "spd_1346_Y488D",
    "gene_a": "mltG(Y488D)",
    "gene_b_locus": "spd_1092",
    "gene_b": "rodZ",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (lytic transglycosylase)",
    "func_b": "Cell shape determination (RodZ, elongasome scaffold)",
    "validation": "confirmed_in_study",
    "pmid": "26933838",
    "doi": "10.1111/mmi.13359",
    "quote": "mltG(Y488D) suppresses DeltarodZ; peripheral PG synthesis"
  },
  {
    "id": "GI057",
    "gene_a_locus": "spd_1346_Y488D",
    "gene_a": "mltG(Y488D)",
    "gene_b_locus": "spd_1166",
    "gene_b": "rodA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (lytic transglycosylase)",
    "func_b": "Cell wall biogenesis (RodA, lipid II flippase)",
    "validation": "confirmed_in_study",
    "pmid": "26933838",
    "doi": "10.1111/mmi.13359",
    "quote": "mltG(Y488D) suppresses DeltarodA; PBP2b:RodA peripheral PG complex"
  },
  {
    "id": "GI058",
    "gene_a_locus": "spd_0336",
    "gene_a": "pbp1a",
    "gene_b_locus": "spd_1346",
    "gene_b": "mltG",
    "class": "positive",
    "subtype": "synthetic_viable",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (aPBP)",
    "func_b": "Cell wall biogenesis (lytic transglycosylase)",
    "validation": "confirmed_in_study",
    "pmid": "26933838",
    "doi": "10.1111/mmi.13359",
    "quote": "Deltapbp1a DeltamltG double mutant; synthetic viable; extends suppression to DeltamreCD and DeltarodZ"
  },
  {
    "id": "GI059",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative (>500 colonies)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpA, KH-domain, post-transcriptional regulator)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpA suppresses Deltapbp2b by overproducing FtsA (~2.6-fold); requires ftsA 5-UTR"
  },
  {
    "id": "GI060",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_1093-1094",
    "gene_b": "mreCD",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpA)",
    "func_b": "Cell shape determination (elongasome)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpA suppresses DeltamreCD; peripheral PG synthesis"
  },
  {
    "id": "GI061",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_1092",
    "gene_b": "rodZ",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpA)",
    "func_b": "Cell shape determination (RodZ)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpA suppresses DeltarodZ"
  },
  {
    "id": "GI062",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_1166",
    "gene_b": "rodA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpA)",
    "func_b": "Cell wall biogenesis (RodA)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpA suppresses DeltarodA"
  },
  {
    "id": "GI063",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_1346",
    "gene_b": "mltG",
    "class": "negative",
    "subtype": "aggravating",
    "method": "classical_genetics",
    "score": "qualitative (0 colonies)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "RNA binding (KhpA)",
    "func_b": "Cell wall biogenesis (lytic transglycosylase)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpA does NOT suppress DeltamltG; DeltakhpA mltG(Y488D) double grows much slower than singles; aggravating"
  },
  {
    "id": "GI064",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_1219",
    "gene_b": "gpsB",
    "class": "positive",
    "subtype": "partial_suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "RNA binding (KhpA)",
    "func_b": "Cell division (GpsB adapter)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpA partially suppresses DeltaqpsB; slower growth elongated cells"
  },
  {
    "id": "GI065",
    "gene_a_locus": "spd_1849",
    "gene_a": "khpB",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative (>500 colonies)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpB/EloR, JAG domain)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "independently_replicated",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpB suppresses Deltapbp2b; same mechanism as DeltakhpA (FtsA overproduction)"
  },
  {
    "id": "GI066",
    "gene_a_locus": "spd_1849",
    "gene_a": "khpB",
    "gene_b_locus": "spd_1093-1094",
    "gene_b": "mreCD",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpB/EloR)",
    "func_b": "Cell shape determination (elongasome)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "DeltakhpB suppresses DeltamreCD"
  },
  {
    "id": "GI067",
    "gene_a_locus": "spd_0675",
    "gene_a": "khpA",
    "gene_b_locus": "spd_1849",
    "gene_b": "khpB",
    "class": "positive",
    "subtype": "complex_partner",
    "method": "classical_genetics+co-IP",
    "score": "co-IP silver staining",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI broth)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "RNA binding (KhpA)",
    "func_b": "RNA binding (KhpB/EloR)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "KhpA and KhpB co-immunoprecipitate each other; direct complex; exact phenocopy of growth/morphology"
  },
  {
    "id": "GI068",
    "gene_a_locus": "spd_0675+spd_1849",
    "gene_a": "khpAB_complex",
    "gene_b_locus": "spd_0067",
    "gene_b": "ftsA",
    "class": "negative",
    "subtype": "post-transcriptional_repression",
    "method": "classical_genetics+RIP-Seq",
    "score": "RIP-Seq + western",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI broth)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding (KhpA/B complex)",
    "func_b": "Cell division (FtsA, actin-like ATPase)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "KhpA/B negatively regulates ftsA post-transcriptionally via ftsA 5-UTR; FtsA OE is necessary and sufficient for suppression"
  },
  {
    "id": "GI069",
    "gene_a_locus": "spd_0067",
    "gene_a": "ftsA",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative (OE + Zn)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar + Zn2+)",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell division (FtsA)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "confirmed_in_study",
    "pmid": "28941257",
    "doi": "10.1111/mmi.13847",
    "quote": "FtsA overproduction (~2.6x) suppresses Deltapbp2b; sufficient mechanism"
  },
  {
    "id": "GI070",
    "gene_a_locus": "spr1851",
    "gene_a": "eloR",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "R6",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding/regulation (EloR=KhpB=JAG, elongasome regulator)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "independently_replicated",
    "pmid": "28710862",
    "doi": "10.1111/mmi.13748",
    "quote": "Identification of Spr1851 (EloR) as suppressor of Deltapbp2b lethality; inactivation removes requirement for PBP2b"
  },
  {
    "id": "GI071",
    "gene_a_locus": "spr1851",
    "gene_a": "eloR",
    "gene_b_locus": "spd_1166",
    "gene_b": "rodA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "R6",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding/regulation (EloR=KhpB)",
    "func_b": "Cell wall biogenesis (RodA)",
    "validation": "confirmed_in_study",
    "pmid": "28710862",
    "doi": "10.1111/mmi.13748",
    "quote": "EloR inactivation removes requirement for RodA; EloR-PBP2b-RodA in same functional network"
  },
  {
    "id": "GI072",
    "gene_a_locus": "spd_1292",
    "gene_a": "stkP",
    "gene_b_locus": "spr1851",
    "gene_b": "eloR",
    "class": "positive",
    "subtype": "phosphorylation",
    "method": "classical_genetics+biochemistry",
    "score": "phospho-Thr T89",
    "pval": "n/a",
    "strain": "R6",
    "condition": "in vitro (BHI broth)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (StkP, Ser/Thr kinase)",
    "func_b": "RNA binding/regulation (EloR=KhpB)",
    "validation": "confirmed_in_study",
    "pmid": "28710862",
    "doi": "10.1111/mmi.13748",
    "quote": "StkP phosphorylates EloR on threonine T89; phosphorylated EloR stimulates cell elongation"
  },
  {
    "id": "GI073",
    "gene_a_locus": "spr1851_T89E",
    "gene_a": "eloR(T89E)",
    "gene_b_locus": "spd_1094",
    "gene_b": "mreC",
    "class": "positive",
    "subtype": "suppressor_of_toxicity",
    "method": "classical_genetics",
    "score": "qualitative (spontaneous)",
    "pval": "n/a",
    "strain": "R6",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "RNA binding/regulation (EloR phosphomimetic)",
    "func_b": "Cell shape determination (MreC elongasome)",
    "validation": "confirmed_in_study",
    "pmid": "28710862",
    "doi": "10.1111/mmi.13748",
    "quote": "EloR(T89E) phosphomimetic not tolerated; MreC truncation suppresses phosphomimetic EloR toxicity"
  },
  {
    "id": "GI074",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_1292",
    "gene_b": "stkP",
    "class": "positive",
    "subtype": "shared_pathway",
    "method": "classical_genetics",
    "score": "qualitative (overlapping suppressors)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell division (GpsB, adapter protein)",
    "func_b": "Signal transduction (StkP, Ser/Thr kinase)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "DeltaqpsB and DeltastkP suppressors overlap; 25/32 DeltaqpsB suppressors are chromosomal duplications containing murZ or murA"
  },
  {
    "id": "GI075",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_0967",
    "gene_b": "murZ",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics+proteomics",
    "score": "transformation + western",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "Cell wall biogenesis (MurZ/MurA2, UDP-MurNAc)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "~2-4x MurZ increase suppresses DeltaqpsB; overproduction of MurZ bypasses GpsB/StkP requirement"
  },
  {
    "id": "GI076",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_1764",
    "gene_b": "murA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "Cell wall biogenesis (MurA, UDP-MurNAc)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "~4-10x MurA increase suppresses DeltaqpsB; higher dosage required vs. MurZ"
  },
  {
    "id": "GI077",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_0018",
    "gene_b": "ireB",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative (ireB Q84STOP or delta)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "Signal transduction (IreB/ReoM, MurZ inhibitor)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "ireB truncation/deletion suppresses DeltaqpsB; unphosphorylated IreB inhibits MurZ/MurA activity"
  },
  {
    "id": "GI078",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_0087",
    "gene_b": "phpP",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative (5 phpP alleles)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "Signal transduction (PhpP, phosphatase)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "phpP missense mutations suppress DeltaqpsB by restoring pThr; phosphatase inactivation"
  },
  {
    "id": "GI079",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_0675",
    "gene_b": "khpA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics+proteomics",
    "score": "qualitative + proteomics",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "RNA binding (KhpA)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "DeltakhpA suppresses DeltaqpsB; mechanism via ~1.4-1.8x MurZ overproduction (post-transcriptional)"
  },
  {
    "id": "GI080",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_1849",
    "gene_b": "khpB",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics+proteomics",
    "score": "qualitative + proteomics",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "RNA binding (KhpB/EloR)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "DeltakhpB suppresses DeltaqpsB via MurZ overproduction; requires murZ+ (not murA)"
  },
  {
    "id": "GI081",
    "gene_a_locus": "spd_1292",
    "gene_a": "stkP",
    "gene_b_locus": "spd_0967",
    "gene_b": "murZ",
    "class": "positive",
    "subtype": "strong_suppressor",
    "method": "classical_genetics",
    "score": "qualitative (full WT colony restoration)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (StkP)",
    "func_b": "Cell wall biogenesis (MurZ)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "murZ(D280Y) strongly suppresses DeltastkP; full WT colonies and morphology restoration"
  },
  {
    "id": "GI082",
    "gene_a_locus": "spd_0018",
    "gene_a": "ireB",
    "gene_b_locus": "spd_0967",
    "gene_b": "murZ",
    "class": "negative",
    "subtype": "enzymatic_inhibition",
    "method": "biochemistry + genetics",
    "score": "activity assay + epistasis",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro/in vivo",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (IreB/ReoM, inhibitor)",
    "func_b": "Cell wall biogenesis (MurZ)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "Unphosphorylated IreB inhibits MurZ and MurA enzymatic activity (not protein amount)"
  },
  {
    "id": "GI083",
    "gene_a_locus": "spd_0967",
    "gene_a": "murZ",
    "gene_b_locus": "spd_1764",
    "gene_b": "murA",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "classical_genetics",
    "score": "qualitative (0 colonies)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (MurZ)",
    "func_b": "Cell wall biogenesis (MurA)",
    "validation": "independently_replicated",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "murZ and murA synthetic lethal; both UDP-GlcNAc carboxyvinyltransferases required"
  },
  {
    "id": "GI084",
    "gene_a_locus": "spd_1292",
    "gene_a": "stkP",
    "gene_b_locus": "spd_1849",
    "gene_b": "khpB",
    "class": "positive",
    "subtype": "phosphorylation",
    "method": "classical_genetics+biochemistry",
    "score": "in vivo phospho-T89",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI broth)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (StkP)",
    "func_b": "RNA binding (KhpB/EloR)",
    "validation": "confirmed_in_study",
    "pmid": "37452010",
    "doi": "10.1111/mmi.15122",
    "quote": "StkP phosphorylates KhpB (EloR) at T89; part of GpsB-StkP signaling network"
  },
  {
    "id": "GI085",
    "gene_a_locus": "spd_1821",
    "gene_a": "pbp2a",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "classical_genetics+Tn-seq",
    "score": "Tn-seq + transformation",
    "pval": "<0.01",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (aPBP, class A PBP)",
    "func_b": "Cell wall biogenesis (aPBP, class A PBP)",
    "validation": "independently_replicated",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "Strain lacking both PBP1a and PBP2a could not be isolated; synthetically lethal pair"
  },
  {
    "id": "GI086",
    "gene_a_locus": "spd_0876",
    "gene_a": "macP",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "classical_genetics+Tn-seq",
    "score": "Tn-seq + conditional depletion",
    "pval": "<0.01",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (MacP, aPBP cofactor)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "Cells lacking MacP required pbp1a induction for growth; MacP-PBP1a synthetic lethal"
  },
  {
    "id": "GI087",
    "gene_a_locus": "spd_1292",
    "gene_a": "stkP",
    "gene_b_locus": "spd_0876",
    "gene_b": "macP",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics+biochemistry",
    "score": "transformation + conditional depletion",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (StkP)",
    "func_b": "Cell wall biogenesis (MacP cofactor)",
    "validation": "confirmed_in_study",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "DeltastkP suppresses synthetic lethality of DeltamacP cells depleted of PBP1a"
  },
  {
    "id": "GI088",
    "gene_a_locus": "spd_1292",
    "gene_a": "stkP",
    "gene_b_locus": "spd_0876",
    "gene_b": "macP",
    "class": "positive",
    "subtype": "phosphorylation",
    "method": "biochemistry",
    "score": "in vivo phospho-T32",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI broth)",
    "ess_a": "essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (StkP)",
    "func_b": "Cell wall biogenesis (MacP)",
    "validation": "confirmed_in_study",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "StkP phosphorylates MacP at T32; phosphorylation required for MacP to activate PBP2a"
  },
  {
    "id": "GI089",
    "gene_a_locus": "spd_0876",
    "gene_a": "macP",
    "gene_b_locus": "spd_1821",
    "gene_b": "pbp2a",
    "class": "positive",
    "subtype": "cofactor_activation",
    "method": "biochemistry (BACTH + co-IP)",
    "score": "BACTH + co-IP",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI broth)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (MacP cofactor)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "MacP directly interacts with PBP2a; required for PBP2a in vivo activity"
  },
  {
    "id": "GI090",
    "gene_a_locus": "spd_0747",
    "gene_a": "cozE",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "positive",
    "subtype": "functional_rescue",
    "method": "Tn-seq epistasis",
    "score": "Tn-seq (cozE insertions enriched in Deltapbp1a)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (CozE)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "cozE essential-like in WT; readily inactivated in Deltapbp1a background (not synthetic lethal)"
  },
  {
    "id": "GI091",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_1821",
    "gene_b": "pbp2a",
    "class": "positive",
    "subtype": "functional_requirement",
    "method": "classical_genetics",
    "score": "conditional genetics",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "29487215",
    "doi": "10.1073/pnas.1715218115",
    "quote": "GpsB required for PBP2a activity (genetic analysis); GpsB-StkP-MacP-PBP2a pathway"
  },
  {
    "id": "GI092",
    "gene_a_locus": "spd_1219",
    "gene_a": "gpsB",
    "gene_b_locus": "spd_0336",
    "gene_b": "pbp1a",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "classical_genetics",
    "score": "qualitative (0 colonies)",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell division (GpsB)",
    "func_b": "Cell wall biogenesis (aPBP)",
    "validation": "confirmed_in_study",
    "pmid": "28010038",
    "doi": "10.1111/mmi.13613",
    "quote": "DeltaqpsB mutations are synthetically lethal with Deltapbp1a; GpsB activates PBP2a activity"
  },
  {
    "id": "GI093",
    "gene_a_locus": "spd_0087",
    "gene_a": "phpP",
    "gene_b_locus": "spd_1219",
    "gene_b": "gpsB",
    "class": "positive",
    "subtype": "suppressor",
    "method": "classical_genetics",
    "score": "qualitative",
    "pval": "n/a",
    "strain": "D39 \u0394cps",
    "condition": "in vitro (BHI agar)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Signal transduction (PhpP phosphatase)",
    "func_b": "Cell division (GpsB)",
    "validation": "independently_replicated",
    "pmid": "28010038",
    "doi": "10.1111/mmi.13613",
    "quote": "Essentiality of DeltaqpsB suppressed by inactivation of PhpP phosphatase; restores protein phosphorylation levels"
  },
  {
    "id": "GI094",
    "gene_a_locus": "spd_0006",
    "gene_a": "pbp2x",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "compensatory",
    "method": "classical_genetics",
    "score": "competitive fitness assay",
    "pval": "n/a",
    "strain": "Cp1015; D39",
    "condition": "in vitro + in vivo (mouse); penicillin/cefotaxime stress",
    "ess_a": "essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (bPBP, beta-lactam resistance)",
    "func_b": "Cell wall biogenesis (bPBP, beta-lactam resistance)",
    "validation": "confirmed_in_study",
    "pmid": "21379570",
    "doi": "10.1371/journal.ppat.1002000",
    "quote": "Fitness cost and cell division defects conferred by pbp2b mutations fully compensated by acquisition of pbp2x and pbp1a mutations"
  },
  {
    "id": "GI095",
    "gene_a_locus": "spd_0336",
    "gene_a": "pbp1a",
    "gene_b_locus": "spd_0582",
    "gene_b": "pbp2b",
    "class": "positive",
    "subtype": "compensatory",
    "method": "classical_genetics",
    "score": "competitive fitness assay",
    "pval": "n/a",
    "strain": "Cp1015; D39",
    "condition": "in vitro + in vivo; antibiotic stress",
    "ess_a": "non-essential",
    "ess_b": "essential",
    "func_a": "Cell wall biogenesis (aPBP)",
    "func_b": "Cell wall biogenesis (bPBP)",
    "validation": "confirmed_in_study",
    "pmid": "21379570",
    "doi": "10.1371/journal.ppat.1002000",
    "quote": "pbp2b mutation fitness cost compensated by acquisition of pbp1a mutations"
  },
  {
    "id": "GI096",
    "gene_a_locus": "multiple",
    "gene_a": "genome-wide",
    "gene_b_locus": "multiple (5 query genes)",
    "gene_b": "genome-wide",
    "class": "mixed",
    "subtype": "alleviating/aggravating",
    "method": "Tn-seq",
    "score": "log-ratio fitness scores",
    "pval": "FDR-controlled",
    "strain": "TIGR4",
    "condition": "in vitro (multiple conditions)",
    "ess_a": "mixed",
    "ess_b": "mixed",
    "func_a": "Mixed (all functional categories)",
    "func_b": "Mixed",
    "validation": "confirmed_in_study",
    "pmid": "19767758",
    "doi": "10.1038/nmeth.1377",
    "quote": "Genome-wide screen for genetic interactions of five query genes identified both alleviating and aggravating interactions divided into seven distinct categories (Tn-seq method paper with primary data)"
  },
  {
    "id": "GI097",
    "gene_a_locus": "spd_0232",
    "gene_a": "cpsA",
    "gene_b_locus": "spd_0319",
    "gene_b": "walK",
    "class": "negative",
    "subtype": "synthetic_lethal",
    "method": "Dual_Tn-seq+classical_genetics",
    "score": "dual Tn-seq + transformation",
    "pval": "<0.01",
    "strain": "D39W",
    "condition": "in vitro (BHI)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (CpsA, putative capsule ligase)",
    "func_b": "Signal transduction (WalK, two-component sensor kinase)",
    "validation": "confirmed_in_study",
    "pmid": "41929132",
    "doi": "10.64898/2026.03.25.714115",
    "quote": "Strong negative genetic interaction between genes encoding putative capsule ligase CpsA and WalK histidine kinase"
  },
  {
    "id": "GI098",
    "gene_a_locus": "spd_0329",
    "gene_a": "pcsB",
    "gene_b_locus": "spd_0232",
    "gene_b": "cpsA",
    "class": "positive",
    "subtype": "suppressor",
    "method": "Dual_Tn-seq+classical_genetics",
    "score": "dual Tn-seq + OE rescue",
    "pval": "n/a",
    "strain": "D39W",
    "condition": "in vitro (BHI)",
    "ess_a": "non-essential",
    "ess_b": "non-essential",
    "func_a": "Cell wall biogenesis (PcsB, hydrolase)",
    "func_b": "Cell wall biogenesis (CpsA)",
    "validation": "confirmed_in_study",
    "pmid": "41929132",
    "doi": "10.64898/2026.03.25.714115",
    "quote": "Overexpression of PG hydrolase pcsB restored growth of strains lacking cpsA and walK"
  },
  {
    "id": "GI099",
    "gene_a_locus": "multiple",
    "gene_a": "antibiotic_susceptibility_genes",
    "gene_b_locus": "multiple",
    "gene_b": "genome-wide_network",
    "class": "mixed",
    "subtype": "alleviating/aggravating",
    "method": "Tn-seq",
    "score": "log-ratio fitness",
    "pval": "FDR-controlled",
    "strain": "D39",
    "condition": "in vitro (20 antibiotics) + in vivo",
    "ess_a": "mixed",
    "ess_b": "mixed",
    "func_a": "Multiple functional categories",
    "func_b": "Multiple functional categories",
    "validation": "confirmed_in_study",
    "pmid": "35672367",
    "doi": "10.1038/s41467-022-30967-4",
    "quote": "Genome-wide atlas of drug susceptibility determinants; genetic interaction network connecting cellular processes and genes of unknown function under 20 antibiotic conditions"
  }
];
